name: Tell me who are you!

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]

jobs:
  test:
    if: contains(github.event.pull_request.labels.*.name, 'run-test') || github.event_name != 'pull_request_target' || (! github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on branch
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Checkout on PR merge commit
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
      - name: My test
        run: |
          echo "running!"
          echo ${{ secrets.TELL_ME_WHO_ARE_YOU }}
          echo ${{ github.event.pull_request.head.sha }}
