name: Test disk space

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum'
          path: optimum

      - name: Free disk space
        run: |
          df -h
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n
          sudo apt-get update
          sudo apt-get install -y wajig
          sudo wajig large
          sudo apt-get remove -y '^dotnet.*'
          sudo apt-get remove -y '^aspnetcore.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y azure-cli google-chrome-stable firefox powershell mono-devel
          df -h
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get clean
          df -h
          echo "https://github.com/actions/virtual-environments/issues/709"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          echo "remove big /usr/local"
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
          df -h
          sudo rm -rf /usr/share/dotnet/sdk > /dev/null 2>&1
          sudo rm -rf /usr/share/dotnet/shared > /dev/null 2>&1
          sudo rm -rf /usr/share/swift > /dev/null 2>&1
          df -h
