name: Test disk space

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'huggingface/optimum'
          path: optimum

      - name: Free disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get purge -y '^apache.*'
          sudo apt-get purge -y '^imagemagick.*'
          sudo apt-get purge -y '^dotnet.*'
          sudo apt-get purge -y '^aspnetcore.*'
          sudo apt-get purge -y 'php.*'
          sudo apt-get purge -y '^temurin.*'
          sudo apt-get purge -y '^mysql.*'
          sudo apt-get purge -y '^java.*'
          sudo apt-get purge -y '^openjdk.*'
          sudo apt-get purge -y microsoft-edge-stable google-cloud-cli azure-cli google-chrome-stable firefox powershell mono-devel
          df -h
          sudo apt-get autoremove -y >/dev/null 2>&1
          sudo apt-get clean
          df -h
          echo "https://github.com/actions/virtual-environments/issues/709"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          echo "remove big /usr/local"
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android >/dev/null 2>&1
          df -h
          echo "remove /usr/share leftovers"
          sudo rm -rf /usr/share/dotnet/sdk > /dev/null 2>&1
          sudo rm -rf /usr/share/dotnet/shared > /dev/null 2>&1
          sudo rm -rf /usr/share/swift > /dev/null 2>&1
          df -h
          echo "remove /usr/share leftovers"
          sudo rm -rf /var/lib/mysql > /dev/null 2>&1
          sudo rm -rf /home/runner/.dotnet > /dev/null 2>&1
          sudo rm -rf /home/runneradmin/.dotnet > /dev/null 2>&1
          sudo rm -rf /etc/skel/.dotnet > /dev/null 2>&1
          sudo rm -rf /usr/local/.ghcup > /dev/null 2>&1
          sudo rm -rf /usr/local/aws-cli > /dev/null 2>&1
          df -h
          echo "print du"
          sudo du -m --max-depth=4 --exclude=/proc/* --exclude=/run/* /* | sort -nr
          echo "packages"
          sudo apt-get update
          sudo apt-get install -y wajig
          sudo wajig large

