on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]
    types: [ opened, synchronize, reopened, labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  authorize:
    if: (github.event.action == 'labeled' && github.event.label.name == 'build-pr-doc') || github.event_name != 'pull_request_target' || (! github.event.pull_request.head.repo.fork)
    runs-on: ubuntu-latest
    steps:
      - run: true
