name: Tell me who are you!

on:
  workflow_dispatch:
  pull_request_target:
    branches: [ main ]

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  test:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        with:
          ref: ${{ refs/pull/${{ github.event.number }}/merge || github.ref }}
        - name: Security: check branch SHA
        run: |
            [[ "$(git rev-parse 'HEAD^')" == "${{ github.event.pull_request.head.sha }}" ]]
      - run: |
          echo "running!"
          echo ${{ secrets.TELL_ME_WHO_ARE_YOU }}
          echo ${{ github.event.pull_request.head.sha }}
